// <auto-generated />
using System;
using Mesa01.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mesa01.Migrations
{
    [DbContext(typeof(Mesa01Context))]
    [Migration("20190627214401_InserirFechamentoBanco")]
    partial class InserirFechamentoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mesa01.Models.Fechamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Banco");

                    b.Property<DateTime>("Data");

                    b.Property<float>("Despesa");

                    b.Property<string>("Empresa");

                    b.Property<int>("Fluxo");

                    b.Property<string>("Operador");

                    b.Property<float>("Taxa");

                    b.Property<string>("Tipo");

                    b.Property<float>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Fechamento");
                });
#pragma warning restore 612, 618
        }
    }
}
